language: android
jdk: oraclejdk8

android:
    components:
        - tools
        - build-tools-25.0.0
        - platform-tools
        - android-16
        - extra-android-m2repository

script:
        - ./gradlew build
before_install:
        - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)