language: android
jdk: oraclejdk8

android:
    components:
        - tools
        - build-tools-25.0.0
        - platform-tools
        - tools
        - android-24
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - extra-google-google_play_services

script:
        - ./gradlew build
before_install:
        - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)